apiVersion: apps/v1
kind: Deployment
metadata:
  name: face-note-book
spec:
  replicas: 2
  selector:
    matchLabels:
      app: face-note-book
  template:
    metadata:
      labels:
        app: face-note-book
    spec:
      containers:
        - name: face-note-book
          image: khanhgaquay/face-note-book:0.0.1
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: face-note-book-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: face-note-book
